-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT  INTO    user_types  (value,description) VALUES  ('FREE','Unpaid Account'),('PREMIUM','Paid Account');
